### ISSUE TITLE
Running costs

### ISSUE THREAD

**Issue by zvictor** [firtoz/GPT-Shell#13]
This tech looks so cool! How does it compare with OpenAI api in terms of cost? How much does it cost on average to run each request?

**Comment by firtoz** [comment]
Thank you :)

The costs are exactly what the OpenAI api charges.

For the initial messages it typically uses 500 ish tokens, so that's around 1 cent per message.

If a conversation grows, the cost will start to rise, as the message history builds up to use more tokens.

Maximum is around 4 cents per message (2k tokens) when the conversations get long enough.

You can configure the max tokens to be lower, so that will be cheaper, but as a result Shell will remember worse.

You can configure the max tokens to be higher so that Shell can remember more, up to around 3.5k tokens per message (+ 500 tokens per response). That will bring the cost to be higher, of course.

**Comment by zvictor** [comment]
Thank you for clarifying. If I understood the project well, it runs on top of the  Wolfram Alpha infrastructure. Thus, the costs you mentioned must come directly from them.

Did I get it right? 😊

**Comment by firtoz** [comment]
The project runs by using OpenAI's GPT-3 Large Language Model. Wolfram Alpha integration is just one of the features. The main costs come from using OpenAI's API. 

Wolfram Alpha integration will also be costly (not as much as OpenAI I think) if we use something other than the simple version, but currently we get 1000 "simple" Wolfram Alpha requests for free :)
